TRAINER:
  MSLR_MILESTONES: [10, 20]
  N_SAMPLES_PER_SUBSET: 40
  CANONICAL_LR: 5.0e-4
  MSLR_GAMMA: 0.1
  MODEL: 'src.models.pose_init'
  NUM_FRAME: 5
  MONITOR_KEY: 'pixel_err_mean'
  SDF_CLAMP: None
  CAMERA_POSE: 'gt'
  EIKONAL_LOSS: 0.1
  TRACK_RUNNING_STATS: True
  NOISE_POSE_STD: 0.01
  TRAIN_SHAPE: False
  TRAIN_POSE: True
  TRAIN_MASK: True
  TRAIN_SCALE: False #shapenet use fixed scale
  USE_OCC: False
  NUM_3D_POINTS: 2048
  RIGID_ALIGN_TO_GT: False
  LIMIT_TEST_NUMBER: 2000

DATASET:
  name: 'shapenet'
  LOAD_DEPTH: True
  IMAGE_WIDTH: 224
  IMAGE_HEIGHT: 224
  DATA_SOURCE: "ShapeNet"
  DATA_ROOT: "./data/shapenet/FvOR_ShapeNet"
  NPZ_ROOT: "./data/shapenet/index/data/"
  TRAIN_LIST_PATH: "./data/shapenet/index/train.txt"
  VAL_LIST_PATH: "./data/shapenet/index/val.txt"
  TEST_LIST_PATH: "./data/shapenet/index/test.txt"

POSE_INIT:
  BACKBONE:
    BACKBONE_TYPE: 'ResNetFPNv2'
    INITIAL_DIM: 64
    BLOCK_DIMS: [64, 128, 256]
  PREDICT_WORLD2CAM: True
