TRAINER:
  MODEL: 'src.models.recon_volume'
  SDF_CLAMP: None
  NUM_FRAME: 5
  EIKONAL_LOSS: 0.1
  TRACK_RUNNING_STATS: True
  CAMERA_POSE: 'gt+noise'
  NOISE_POSE_STD: 0.005
  TRAIN_SHAPE: True
  TRAIN_POSE: True
  TRAIN_MASK: False
  TRAIN_SCALE: False
  USE_OCC: False
  NUM_3D_POINTS: 2048
  RIGID_ALIGN_TO_GT: True
  LIMIT_TEST_NUMBER: 1000
  EVAL_PER_JOINT_STEP: True

BACKBONE:
  PIXEL_FEATURE_DIM: 96

COST_REG_NET:
  NUM_COST_REG_LAYER: 6
  VOLUME_REDUCTION: 'mean'


POSE_REFINE:
  DROP_FOR_INCREASING_ENERGY: False
  JOINT_STEP: 3
  CLAMP_POSE_UPDATE: True
  LAMBDA_REG: 1.0e3
  FLOWNET_NORMALIZE_FEATURE_MAP: True
  POSE_UPDATE_INNER_ITER: 5
  LAMBDA_DAMPING: 100.0

POST_PROCESSING:
  OPTIMIZE_SCALE: True
  JOINT_LR: 2.0e-4

DATASET:
  name: 'shapenet'
  LOAD_DEPTH: True
  IMAGE_WIDTH: 224
  IMAGE_HEIGHT: 224
  SHAPENET_CATEGORY_TEST: ''
  DATA_SOURCE: "ShapeNet"
  DATA_ROOT: "./data/shapenet/FvOR_ShapeNet"
  NPZ_ROOT: "./data/shapenet/index/data/"
  TRAIN_LIST_PATH: "./data/shapenet/index/train.txt"
  VAL_LIST_PATH: "./data/shapenet/index/val.txt"
  TEST_LIST_PATH: "./data/shapenet/index/test.txt"
